//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least 18 years old.
        /// </summary>
        internal static string strBirthDateInvalid {
            get {
                return ResourceManager.GetString("strBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgas.
        /// </summary>
        internal static string strBurgas {
            get {
                return ResourceManager.GetString("strBurgas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string strCar {
            get {
                return ResourceManager.GetString("strCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No found cars in this period.
        /// </summary>
        internal static string strCarsNotFound {
            get {
                return ResourceManager.GetString("strCarsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose database.
        /// </summary>
        internal static string strChooseDatabase {
            get {
                return ResourceManager.GetString("strChooseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new database.
        /// </summary>
        internal static string strCreateNewDatabase {
            get {
                return ResourceManager.GetString("strCreateNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists..
        /// </summary>
        internal static string strDatabaseExists {
            get {
                return ResourceManager.GetString("strDatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string strDatabaseName {
            get {
                return ResourceManager.GetString("strDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database settings.
        /// </summary>
        internal static string strDatabaseSettings {
            get {
                return ResourceManager.GetString("strDatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        internal static string strDateOfBirth {
            get {
                return ResourceManager.GetString("strDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Days.
        /// </summary>
        internal static string strDays {
            get {
                return ResourceManager.GetString("strDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical car.
        /// </summary>
        internal static string strECar {
            get {
                return ResourceManager.GetString("strECar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        internal static string strEmailInvalid {
            get {
                return ResourceManager.GetString("strEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with:.
        /// </summary>
        internal static string strFill {
            get {
                return ResourceManager.GetString("strFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        internal static string strFreight {
            get {
                return ResourceManager.GetString("strFreight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date is not correct.
        /// </summary>
        internal static string strFromDateInvalid {
            get {
                return ResourceManager.GetString("strFromDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data!.
        /// </summary>
        internal static string strInvalidData {
            get {
                return ResourceManager.GetString("strInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string strLastName {
            get {
                return ResourceManager.GetString("strLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must be at least 2 characters.
        /// </summary>
        internal static string strLastNameInvalid {
            get {
                return ResourceManager.GetString("strLastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  l/km.
        /// </summary>
        internal static string strLkm {
            get {
                return ResourceManager.GetString("strLkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 2 characters.
        /// </summary>
        internal static string strNameInvalid {
            get {
                return ResourceManager.GetString("strNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to server..
        /// </summary>
        internal static string strNoConnection {
            get {
                return ResourceManager.GetString("strNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string strOrder {
            get {
                return ResourceManager.GetString("strOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        internal static string strPeriod {
            get {
                return ResourceManager.GetString("strPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period is invalid.
        /// </summary>
        internal static string strPeriodInvalid {
            get {
                return ResourceManager.GetString("strPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string strPersonalData {
            get {
                return ResourceManager.GetString("strPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string strPhone {
            get {
                return ResourceManager.GetString("strPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is not valid.
        /// </summary>
        internal static string strPhoneInvalid {
            get {
                return ResourceManager.GetString("strPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of hire:.
        /// </summary>
        internal static string strPlaceHire {
            get {
                return ResourceManager.GetString("strPlaceHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of return:.
        /// </summary>
        internal static string strPlaceReturn {
            get {
                return ResourceManager.GetString("strPlaceReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plovdiv.
        /// </summary>
        internal static string strPlovdiv {
            get {
                return ResourceManager.GetString("strPlovdiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for .
        /// </summary>
        internal static string strPriceFor {
            get {
                return ResourceManager.GetString("strPriceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string strReservation {
            get {
                return ResourceManager.GetString("strReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruse.
        /// </summary>
        internal static string strRuse {
            get {
                return ResourceManager.GetString("strRuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search now.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string strServerName {
            get {
                return ResourceManager.GetString("strServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofia.
        /// </summary>
        internal static string strSofia {
            get {
                return ResourceManager.GetString("strSofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation saved successfully.
        /// </summary>
        internal static string strSuccessfulReservation {
            get {
                return ResourceManager.GetString("strSuccessfulReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent a car.
        /// </summary>
        internal static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date is not correct.
        /// </summary>
        internal static string strToDateInvalid {
            get {
                return ResourceManager.GetString("strToDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To selection.
        /// </summary>
        internal static string strToSelect {
            get {
                return ResourceManager.GetString("strToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price:.
        /// </summary>
        internal static string strTotalPrice {
            get {
                return ResourceManager.GetString("strTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string strUsername {
            get {
                return ResourceManager.GetString("strUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varna.
        /// </summary>
        internal static string strVarna {
            get {
                return ResourceManager.GetString("strVarna", resourceCulture);
            }
        }
    }
}
